FROM node:18-alpine

WORKDIR /app

# Installer Angular CLI + Prettier + ESLint globalement
RUN npm install -g @angular/cli prettier eslint

# Ajout des arguments UID/GID
ARG USER_ID=1000
ARG GROUP_ID=1000

# Créer un utilisateur non-root
RUN deluser --remove-home node \
  && addgroup -g $GROUP_ID nodeuser \
  && adduser -u $USER_ID -G nodeuser -s /bin/sh -D nodeuser

# Passer temporairement en root
USER root

# Copier package.json + lock en premier pour le cache
COPY package.json package-lock.json ./

# Donner les bons droits
RUN chown -R nodeuser:nodeuser /app

# Revenir à l’utilisateur nodeuser
USER nodeuser

# Installer les dépendances (sera écrasé ensuite par volume mais nécessaire au build)
RUN npm install

# Copier le reste du projet
COPY . .

# Commande remplacée par docker-compose, donc pas utile ici
