FROM node:18-alpine

WORKDIR /app

# Installer NestJS CLI globalement
RUN npm install -g @nestjs/cli

# Ajout des arguments pour les UID et GID
ARG USER_ID=1000
ARG GROUP_ID=1000

# Création d’un utilisateur non-root
RUN deluser --remove-home node \
  && addgroup -g $GROUP_ID nodeuser \
  && adduser -u $USER_ID -G nodeuser -s /bin/sh -D nodeuser \
  && chown -R nodeuser:nodeuser /app

# Passer temporairement en root pour copier les fichiers
USER root

# Copier package.json AVANT d'installer les dépendances
COPY package.json package-lock.json ./

RUN chown -R nodeuser:nodeuser /app

# Passer à l'utilisateur non-root
USER nodeuser

# Installation des dépendances
RUN npm install

# Copier le reste du projet
COPY . .

# Forcer `npm install`, générer Prisma et démarrer l’API
CMD sh -c "npm install && npx prisma generate && npx prisma migrate deploy && npm run start:dev"
